version: "3.9"

services:
   web:
      container_name: front
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 3000:3000
      command: bash -c "yarn install && yarn start"
      volumes:
         - :/app
